name: BatteryMonitor
options:
  bundleIdPrefix: com.stephen
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.6"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  BatteryMonitor:
    type: application
    platform: macOS
    sources:
      - path: BatteryMonitor
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stephen.BatteryMonitor
        PRODUCT_NAME: BatteryMonitor
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "2"
        CODE_SIGN_ENTITLEMENTS: BatteryMonitor/BatteryMonitor.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 6WLUSLD79F
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_CFBundleDisplayName: "电池监控中心"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Stephen. All rights reserved."
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: NO
    entitlements:
      path: BatteryMonitor/BatteryMonitor.entitlements
      properties:
        com.apple.security.app-sandbox: true
