import Foundation

// MARK: - Localization System

enum L10n {
    static var currentLanguage: String {
        let code = Locale.current.language.languageCode?.identifier ?? "en"
        let script = Locale.current.language.script?.identifier
        if code == "zh" {
            return script == "Hant" ? "zh-Hant" : "zh-Hans"
        }
        return code
    }

    static func string(_ key: String) -> String {
        let lang = currentLanguage
        return table[lang]?[key] ?? table["en"]?[key] ?? key
    }
}

func L(_ key: String) -> String { L10n.string(key) }

func L(_ key: String, _ args: CVarArg...) -> String {
    String(format: L10n.string(key), arguments: args)
}

// MARK: - Translation Table

private let table: [String: [String: String]] = [
"en": [
    // App
    "app.title": "Battery Monitor",
    "app.subtitle": "Real-Time Battery Dashboard",
    "app.subtitle.model": "%@ · Real-Time Dashboard",
    "app.live": "LIVE",
    // Status tips
    "status.charging": "Charging at %.1fW · Adapter %dW",
    "status.ac_full": "Connected · Battery Full",
    "status.ac_not_charging": "Connected · Not Charging",
    "status.discharging": "Unplugged · Discharging %.1fW",
    // Gauge
    "gauge.full": "until full",
    "gauge.ac": "AC Power",
    "gauge.battery": "On Battery",
    "gauge.cycles_unit": "cycles",
    "gauge.a11y_label": "Battery Level",
    "gauge.a11y_charging": "Charging",
    "gauge.a11y_battery": "On Battery",
    // Stats grid
    "stat.charge_power": "Charge Power",
    "stat.discharge_power": "Discharge Power",
    "stat.realtime_charging": "Active",
    "stat.not_charging": "Idle",
    "stat.on_battery": "On Battery",
    "stat.adapter": "Adapter",
    "stat.not_connected": "N/A",
    "stat.usbc": "USB-C",
    "stat.unplugged": "Unplugged",
    "stat.temperature": "Temperature",
    "stat.temp_high": "High",
    "stat.temp_normal": "Normal",
    "stat.cycles": "Cycle Count",
    "stat.cycle_good": "Good",
    "stat.cycle_aging": "Normal Aging",
    "stat.cycle_check": "Check Advised",
    "stat.health": "Health",
    "stat.health_excellent": "Excellent",
    "stat.health_good": "Good",
    "stat.condition": "Condition",
    "stat.system_check": "System Check",
    // Condition
    "condition.normal": "Normal",
    "condition.replace_soon": "Service Recommended",
    "condition.replace_now": "Replace Now",
    // Realtime
    "rt.title": "Real-Time Monitor",
    "rt.voltage": "Voltage",
    "rt.amperage": "Current",
    "rt.power": "Power",
    "rt.temperature": "Temp",
    "rt.percent": "Level",
    "rt.30s": "30s",
    "rt.1m": "1m",
    "rt.3m": "3m",
    "rt.interval": "Sampled every 3s",
    "rt.collecting": "Collecting data...",
    "rt.collecting_hint": "Sampling every 3 seconds",
    "rt.time": "Time",
    "rt.y_voltage": "Voltage (V)",
    "rt.y_amperage": "Current (mA)",
    "rt.y_power": "Power (W)",
    "rt.y_temperature": "Temp (°C)",
    "rt.y_percent": "Level (%)",
    // History
    "hist.title": "Charge History",
    "hist.refresh": "Refresh",
    "hist.analyzing": "Analyzing charge log...",
    "hist.empty": "No charge history yet",
    "hist.empty_hint": "Charge your Mac then tap Refresh",
    "hist.rate_chart": "Charge Rate Comparison (%/hr)",
    "hist.rate_unit": "%/hr",
    "hist.duration": "%d min · %@",
    // Process
    "proc.title": "Power-Hungry Processes",
    "proc.refresh": "Refresh",
    "proc.cpu_live": "CPU% · Live",
    "proc.loading": "Loading processes...",
    "proc.cpu_trend": "CPU Trend",
    "proc.peak": "Peak",
    "proc.avg": "Avg",
    "proc.interval": "Every 5s · %d pts",
    "proc.collecting": "Collecting samples...",
    // Usage levels (stored in history)
    "usage.heavy": "Heavy Use",
    "usage.moderate": "Moderate Use",
    "usage.light": "Light Use",
    "usage.idle": "Idle/Sleep",
    // Tooltips
    "tip.charge_power": "Real-time power (W) flowing into or out of the battery. Positive = charging, negative = discharging.",
    "tip.adapter": "Rated wattage of the connected power adapter. 0W means no adapter detected.",
    "tip.temperature": "Current battery cell temperature. Normal range: 20–35°C. Above 40°C may throttle performance.",
    "tip.cycles": "Total charge cycles consumed. Apple rates batteries for ~1000 cycles before health drops below 80%.",
    "tip.health": "Current max capacity vs. original design capacity. 100% = brand new. Below 80% = consider replacement.",
    "tip.condition": "System-assessed battery condition based on health metrics and cycle count.",
    "tip.voltage": "Battery terminal voltage. Typical range: 10–13V for MacBook batteries.",
    "tip.amperage": "Charge/discharge current in milliamps. Positive = charging, negative = discharging.",
    "tip.power": "Instantaneous power = |Current| × Voltage. Shows real-time energy flow.",
    "tip.percent": "Current state of charge as percentage of usable capacity.",
    "tip.charge_rate": "How many percent the battery gains per hour. Higher = faster charging.",
    "tip.cpu": "CPU usage percentage of this process. Higher CPU = more power draw.",
    "calculating": "Calculating...",
],

"zh-Hans": [
    "app.title": "电池监控中心",
    "app.subtitle": "实时电池数据看板",
    "app.subtitle.model": "%@ · 实时数据看板",
    "app.live": "实时",
    "status.charging": "正在以 %.1fW 充电 · 适配器 %dW",
    "status.ac_full": "已连接电源 · 电池已充满",
    "status.ac_not_charging": "已连接电源 · 未充电",
    "status.discharging": "充电器已拔掉 · 放电 %.1fW · 重新测算中",
    "gauge.full": "充满",
    "gauge.ac": "已连接电源",
    "gauge.battery": "使用电池",
    "gauge.cycles_unit": "次",
    "gauge.a11y_label": "电池电量",
    "gauge.a11y_charging": "充电中",
    "gauge.a11y_battery": "使用电池",
    "stat.charge_power": "充电功率",
    "stat.discharge_power": "放电功率",
    "stat.realtime_charging": "实时充电",
    "stat.not_charging": "未充电",
    "stat.on_battery": "使用电池",
    "stat.adapter": "适配器",
    "stat.not_connected": "未连接",
    "stat.usbc": "USB-C",
    "stat.unplugged": "充电器已拔掉",
    "stat.temperature": "电池温度",
    "stat.temp_high": "偏高",
    "stat.temp_normal": "正常",
    "stat.cycles": "循环次数",
    "stat.cycle_good": "状态良好",
    "stat.cycle_aging": "正常老化",
    "stat.cycle_check": "建议检测",
    "stat.health": "健康度",
    "stat.health_excellent": "优秀",
    "stat.health_good": "良好",
    "stat.condition": "电池状态",
    "stat.system_check": "系统检测",
    "condition.normal": "正常",
    "condition.replace_soon": "建议更换",
    "condition.replace_now": "立即更换",
    "rt.title": "实时监控",
    "rt.voltage": "电压",
    "rt.amperage": "电流",
    "rt.power": "功率",
    "rt.temperature": "温度",
    "rt.percent": "电量",
    "rt.30s": "30秒",
    "rt.1m": "1分钟",
    "rt.3m": "3分钟",
    "rt.interval": "每3秒采集一次",
    "rt.collecting": "正在采集数据...",
    "rt.collecting_hint": "每3秒采集一次，请稍候",
    "rt.time": "时间",
    "rt.y_voltage": "电压 (V)",
    "rt.y_amperage": "电流 (mA)",
    "rt.y_power": "功率 (W)",
    "rt.y_temperature": "温度 (°C)",
    "rt.y_percent": "电量 (%)",
    "hist.title": "充电历史",
    "hist.refresh": "刷新",
    "hist.analyzing": "正在分析充电日志...",
    "hist.empty": "暂无充电历史记录",
    "hist.empty_hint": "充电后点击「刷新」按钮即可查看",
    "hist.rate_chart": "充电速率对比 (%/小时)",
    "hist.rate_unit": "%/时",
    "hist.duration": "%d分钟 · %@",
    "proc.title": "耗电进程排行",
    "proc.refresh": "刷新",
    "proc.cpu_live": "CPU% · 实时",
    "proc.loading": "正在加载进程列表...",
    "proc.cpu_trend": "CPU 趋势",
    "proc.peak": "峰值",
    "proc.avg": "均值",
    "proc.interval": "每5秒 · %d点",
    "proc.collecting": "正在采集样本，请稍候…",
    "usage.heavy": "重度使用",
    "usage.moderate": "中度使用",
    "usage.light": "轻度使用",
    "usage.idle": "息屏/空闲",
    "tip.charge_power": "电池当前的充电或放电功率（瓦特）。正值表示充电，负值表示放电。",
    "tip.adapter": "已连接电源适配器的额定功率。显示0W表示未检测到适配器。",
    "tip.temperature": "电池电芯当前温度。正常范围20–35°C，超过40°C可能触发降频保护。",
    "tip.cycles": "电池累计完成的充放电循环次数。Apple设计寿命约1000次循环后健康度降至80%以下。",
    "tip.health": "当前最大容量与出厂设计容量的比值。100%为全新状态，低于80%建议更换电池。",
    "tip.condition": "系统根据健康度和循环次数综合评估的电池状态。",
    "tip.voltage": "电池端电压。MacBook电池典型范围10–13V。",
    "tip.amperage": "充放电电流（毫安）。正值表示充电，负值表示放电。",
    "tip.power": "瞬时功率 = |电流| × 电压，反映实时能量流动。",
    "tip.percent": "当前剩余电量占可用容量的百分比。",
    "tip.charge_rate": "每小时充电百分比，数值越高充电越快。受使用强度影响。",
    "tip.cpu": "该进程的CPU占用百分比。占用越高，耗电越多。",
    "calculating": "计算中...",
],

"zh-Hant": [
    "app.title": "電池監控中心",
    "app.subtitle": "即時電池數據看板",
    "app.subtitle.model": "%@ · 即時數據看板",
    "app.live": "即時",
    "status.charging": "正在以 %.1fW 充電 · 配接器 %dW",
    "status.ac_full": "已連接電源 · 電池已充滿",
    "status.ac_not_charging": "已連接電源 · 未充電",
    "status.discharging": "充電器已拔掉 · 放電 %.1fW · 重新測算中",
    "gauge.full": "充滿",
    "gauge.ac": "已連接電源",
    "gauge.battery": "使用電池",
    "gauge.cycles_unit": "次",
    "gauge.a11y_label": "電池電量",
    "gauge.a11y_charging": "充電中",
    "gauge.a11y_battery": "使用電池",
    "stat.charge_power": "充電功率",
    "stat.discharge_power": "放電功率",
    "stat.realtime_charging": "即時充電",
    "stat.not_charging": "未充電",
    "stat.on_battery": "使用電池",
    "stat.adapter": "配接器",
    "stat.not_connected": "未連接",
    "stat.usbc": "USB-C",
    "stat.unplugged": "充電器已拔掉",
    "stat.temperature": "電池溫度",
    "stat.temp_high": "偏高",
    "stat.temp_normal": "正常",
    "stat.cycles": "循環次數",
    "stat.cycle_good": "狀態良好",
    "stat.cycle_aging": "正常老化",
    "stat.cycle_check": "建議檢測",
    "stat.health": "健康度",
    "stat.health_excellent": "優秀",
    "stat.health_good": "良好",
    "stat.condition": "電池狀態",
    "stat.system_check": "系統檢測",
    "condition.normal": "正常",
    "condition.replace_soon": "建議更換",
    "condition.replace_now": "立即更換",
    "rt.title": "即時監控",
    "rt.voltage": "電壓",
    "rt.amperage": "電流",
    "rt.power": "功率",
    "rt.temperature": "溫度",
    "rt.percent": "電量",
    "rt.30s": "30秒",
    "rt.1m": "1分鐘",
    "rt.3m": "3分鐘",
    "rt.interval": "每3秒採集一次",
    "rt.collecting": "正在採集數據...",
    "rt.collecting_hint": "每3秒採集一次，請稍候",
    "rt.time": "時間",
    "rt.y_voltage": "電壓 (V)",
    "rt.y_amperage": "電流 (mA)",
    "rt.y_power": "功率 (W)",
    "rt.y_temperature": "溫度 (°C)",
    "rt.y_percent": "電量 (%)",
    "hist.title": "充電歷史",
    "hist.refresh": "重新整理",
    "hist.analyzing": "正在分析充電日誌...",
    "hist.empty": "暫無充電歷史記錄",
    "hist.empty_hint": "充電後點擊「重新整理」按鈕即可查看",
    "hist.rate_chart": "充電速率對比 (%/小時)",
    "hist.rate_unit": "%/時",
    "hist.duration": "%d分鐘 · %@",
    "proc.title": "耗電行程排行",
    "proc.refresh": "重新整理",
    "proc.cpu_live": "CPU% · 即時",
    "proc.loading": "正在載入行程列表...",
    "proc.cpu_trend": "CPU 趨勢",
    "proc.peak": "峰值",
    "proc.avg": "均值",
    "proc.interval": "每5秒 · %d點",
    "proc.collecting": "正在採集樣本，請稍候…",
    "usage.heavy": "重度使用",
    "usage.moderate": "中度使用",
    "usage.light": "輕度使用",
    "usage.idle": "息屏/閒置",
    "tip.charge_power": "電池當前的充電或放電功率（瓦特）。正值表示充電，負值表示放電。",
    "tip.adapter": "已連接電源配接器的額定功率。顯示0W表示未檢測到配接器。",
    "tip.temperature": "電池電芯當前溫度。正常範圍20–35°C，超過40°C可能觸發降頻保護。",
    "tip.cycles": "電池累計完成的充放電循環次數。Apple設計壽命約1000次循環後健康度降至80%以下。",
    "tip.health": "當前最大容量與出廠設計容量的比值。100%為全新狀態，低於80%建議更換電池。",
    "tip.condition": "系統根據健康度和循環次數綜合評估的電池狀態。",
    "tip.voltage": "電池端電壓。MacBook電池典型範圍10–13V。",
    "tip.amperage": "充放電電流（毫安）。正值表示充電，負值表示放電。",
    "tip.power": "瞬時功率 = |電流| × 電壓，反映即時能量流動。",
    "tip.percent": "當前剩餘電量佔可用容量的百分比。",
    "tip.charge_rate": "每小時充電百分比，數值越高充電越快。受使用強度影響。",
    "tip.cpu": "該行程的CPU佔用百分比。佔用越高，耗電越多。",
    "calculating": "計算中...",
],

"ja": [
    "app.title": "バッテリーモニター",
    "app.subtitle": "リアルタイムバッテリーダッシュボード",
    "app.subtitle.model": "%@ · リアルタイムダッシュボード",
    "app.live": "リアルタイム",
    "status.charging": "%.1fWで充電中 · アダプタ %dW",
    "status.ac_full": "電源接続済み · 満充電",
    "status.ac_not_charging": "電源接続済み · 充電なし",
    "status.discharging": "電源切断 · 放電 %.1fW · 再計算中",
    "gauge.full": "満充電まで",
    "gauge.ac": "電源接続",
    "gauge.battery": "バッテリー駆動",
    "gauge.cycles_unit": "回",
    "gauge.a11y_label": "バッテリー残量",
    "gauge.a11y_charging": "充電中",
    "gauge.a11y_battery": "バッテリー駆動",
    "stat.charge_power": "充電電力",
    "stat.discharge_power": "放電電力",
    "stat.realtime_charging": "充電中",
    "stat.not_charging": "未充電",
    "stat.on_battery": "バッテリー駆動",
    "stat.adapter": "アダプタ",
    "stat.not_connected": "未接続",
    "stat.usbc": "USB-C",
    "stat.unplugged": "電源切断",
    "stat.temperature": "バッテリー温度",
    "stat.temp_high": "高め",
    "stat.temp_normal": "正常",
    "stat.cycles": "サイクル回数",
    "stat.cycle_good": "良好",
    "stat.cycle_aging": "正常な経年劣化",
    "stat.cycle_check": "点検推奨",
    "stat.health": "バッテリー状態",
    "stat.health_excellent": "優秀",
    "stat.health_good": "良好",
    "stat.condition": "バッテリーコンディション",
    "stat.system_check": "システム診断",
    "condition.normal": "正常",
    "condition.replace_soon": "交換推奨",
    "condition.replace_now": "至急交換",
    "rt.title": "リアルタイム監視",
    "rt.voltage": "電圧",
    "rt.amperage": "電流",
    "rt.power": "電力",
    "rt.temperature": "温度",
    "rt.percent": "残量",
    "rt.30s": "30秒",
    "rt.1m": "1分",
    "rt.3m": "3分",
    "rt.interval": "3秒ごとにサンプリング",
    "rt.collecting": "データ収集中...",
    "rt.collecting_hint": "3秒ごとにサンプリング中",
    "rt.time": "時間",
    "rt.y_voltage": "電圧 (V)",
    "rt.y_amperage": "電流 (mA)",
    "rt.y_power": "電力 (W)",
    "rt.y_temperature": "温度 (°C)",
    "rt.y_percent": "残量 (%)",
    "hist.title": "充電履歴",
    "hist.refresh": "更新",
    "hist.analyzing": "充電ログを分析中...",
    "hist.empty": "充電履歴なし",
    "hist.empty_hint": "充電後に「更新」をタップしてください",
    "hist.rate_chart": "充電速度比較 (%/時)",
    "hist.rate_unit": "%/時",
    "hist.duration": "%d分 · %@",
    "proc.title": "電力消費プロセス",
    "proc.refresh": "更新",
    "proc.cpu_live": "CPU% · リアルタイム",
    "proc.loading": "プロセス読込中...",
    "proc.cpu_trend": "CPUトレンド",
    "proc.peak": "ピーク",
    "proc.avg": "平均",
    "proc.interval": "5秒ごと · %d点",
    "proc.collecting": "サンプル収集中…",
    "usage.heavy": "高負荷",
    "usage.moderate": "中負荷",
    "usage.light": "低負荷",
    "usage.idle": "スリープ/アイドル",
    "tip.charge_power": "バッテリーへの充電または放電電力（ワット）。正の値=充電、負の値=放電。",
    "tip.adapter": "接続された電源アダプタの定格出力。0Wはアダプタ未検出。",
    "tip.temperature": "バッテリーセルの現在温度。正常範囲20–35°C、40°C超でパフォーマンス制限の可能性。",
    "tip.cycles": "累積充放電サイクル数。Appleの設計寿命は約1000サイクルで健康度80%以下。",
    "tip.health": "現在の最大容量と設計容量の比率。100%=新品、80%未満=交換推奨。",
    "tip.condition": "健康度とサイクル数に基づくシステム評価。",
    "tip.voltage": "バッテリー端子電圧。MacBookの典型範囲10–13V。",
    "tip.amperage": "充放電電流（ミリアンペア）。正=充電、負=放電。",
    "tip.power": "瞬時電力 = |電流| × 電圧。リアルタイムのエネルギーフロー。",
    "tip.percent": "使用可能容量に対する現在の残量百分比。",
    "tip.charge_rate": "1時間あたりの充電%。高いほど高速充電。使用状況に影響される。",
    "tip.cpu": "このプロセスのCPU使用率。高いほど電力消費大。",
    "calculating": "計算中...",
],

"ko": [
    "app.title": "배터리 모니터",
    "app.subtitle": "실시간 배터리 대시보드",
    "app.subtitle.model": "%@ · 실시간 대시보드",
    "app.live": "실시간",
    "status.charging": "%.1fW 충전 중 · 어댑터 %dW",
    "status.ac_full": "전원 연결됨 · 완전 충전",
    "status.ac_not_charging": "전원 연결됨 · 충전 안 함",
    "status.discharging": "전원 분리 · 방전 %.1fW · 재계산 중",
    "gauge.full": "완충까지",
    "gauge.ac": "전원 연결",
    "gauge.battery": "배터리 사용",
    "gauge.cycles_unit": "회",
    "gauge.a11y_label": "배터리 잔량",
    "gauge.a11y_charging": "충전 중",
    "gauge.a11y_battery": "배터리 사용",
    "stat.charge_power": "충전 전력",
    "stat.discharge_power": "방전 전력",
    "stat.realtime_charging": "충전 중",
    "stat.not_charging": "미충전",
    "stat.on_battery": "배터리 사용",
    "stat.adapter": "어댑터",
    "stat.not_connected": "미연결",
    "stat.usbc": "USB-C",
    "stat.unplugged": "전원 분리됨",
    "stat.temperature": "배터리 온도",
    "stat.temp_high": "높음",
    "stat.temp_normal": "정상",
    "stat.cycles": "사이클 횟수",
    "stat.cycle_good": "양호",
    "stat.cycle_aging": "정상 노후화",
    "stat.cycle_check": "점검 권장",
    "stat.health": "건강도",
    "stat.health_excellent": "우수",
    "stat.health_good": "양호",
    "stat.condition": "배터리 상태",
    "stat.system_check": "시스템 진단",
    "condition.normal": "정상",
    "condition.replace_soon": "교체 권장",
    "condition.replace_now": "즉시 교체",
    "rt.title": "실시간 모니터링",
    "rt.voltage": "전압",
    "rt.amperage": "전류",
    "rt.power": "전력",
    "rt.temperature": "온도",
    "rt.percent": "잔량",
    "rt.30s": "30초",
    "rt.1m": "1분",
    "rt.3m": "3분",
    "rt.interval": "3초마다 샘플링",
    "rt.collecting": "데이터 수집 중...",
    "rt.collecting_hint": "3초마다 샘플링 중",
    "rt.time": "시간",
    "rt.y_voltage": "전압 (V)",
    "rt.y_amperage": "전류 (mA)",
    "rt.y_power": "전력 (W)",
    "rt.y_temperature": "온도 (°C)",
    "rt.y_percent": "잔량 (%)",
    "hist.title": "충전 기록",
    "hist.refresh": "새로고침",
    "hist.analyzing": "충전 로그 분석 중...",
    "hist.empty": "충전 기록 없음",
    "hist.empty_hint": "충전 후 새로고침을 탭하세요",
    "hist.rate_chart": "충전 속도 비교 (%/시간)",
    "hist.rate_unit": "%/시",
    "hist.duration": "%d분 · %@",
    "proc.title": "전력 소비 프로세스",
    "proc.refresh": "새로고침",
    "proc.cpu_live": "CPU% · 실시간",
    "proc.loading": "프로세스 로딩 중...",
    "proc.cpu_trend": "CPU 추세",
    "proc.peak": "최대",
    "proc.avg": "평균",
    "proc.interval": "5초마다 · %d점",
    "proc.collecting": "샘플 수집 중…",
    "usage.heavy": "고부하",
    "usage.moderate": "중부하",
    "usage.light": "저부하",
    "usage.idle": "절전/유휴",
    "tip.charge_power": "배터리 충전 또는 방전 전력(와트). 양수=충전, 음수=방전.",
    "tip.adapter": "연결된 전원 어댑터의 정격 출력. 0W는 어댑터 미감지.",
    "tip.temperature": "배터리 셀 현재 온도. 정상 범위 20–35°C, 40°C 초과 시 성능 제한 가능.",
    "tip.cycles": "누적 충방전 사이클 수. Apple 설계 수명 약 1000사이클 후 건강도 80% 미만.",
    "tip.health": "현재 최대 용량 대 설계 용량 비율. 100%=신품, 80% 미만=교체 권장.",
    "tip.condition": "건강도와 사이클 수 기반 시스템 평가.",
    "tip.voltage": "배터리 단자 전압. MacBook 일반 범위 10–13V.",
    "tip.amperage": "충방전 전류(밀리암페어). 양수=충전, 음수=방전.",
    "tip.power": "순간 전력 = |전류| × 전압. 실시간 에너지 흐름.",
    "tip.percent": "사용 가능 용량 대비 현재 잔량 백분율.",
    "tip.charge_rate": "시간당 충전 %. 높을수록 고속 충전. 사용 강도에 영향받음.",
    "tip.cpu": "이 프로세스의 CPU 사용률. 높을수록 전력 소비 큼.",
    "calculating": "계산 중...",
],

"fr": [
    "app.title": "Moniteur Batterie",
    "app.subtitle": "Tableau de bord batterie temps réel",
    "app.subtitle.model": "%@ · Tableau de bord temps réel",
    "app.live": "EN DIRECT",
    "status.charging": "Charge %.1fW · Adaptateur %dW",
    "status.ac_full": "Connecté · Batterie pleine",
    "status.ac_not_charging": "Connecté · Pas en charge",
    "status.discharging": "Débranché · Décharge %.1fW",
    "gauge.full": "pleine",
    "gauge.ac": "Secteur",
    "gauge.battery": "Sur batterie",
    "gauge.cycles_unit": "cycles",
    "gauge.a11y_label": "Niveau batterie",
    "gauge.a11y_charging": "En charge",
    "gauge.a11y_battery": "Sur batterie",
    "stat.charge_power": "Puissance charge",
    "stat.discharge_power": "Puissance décharge",
    "stat.realtime_charging": "Active",
    "stat.not_charging": "Inactif",
    "stat.on_battery": "Sur batterie",
    "stat.adapter": "Adaptateur",
    "stat.not_connected": "N/A",
    "stat.usbc": "USB-C",
    "stat.unplugged": "Débranché",
    "stat.temperature": "Température",
    "stat.temp_high": "Élevée",
    "stat.temp_normal": "Normale",
    "stat.cycles": "Cycles",
    "stat.cycle_good": "Bon état",
    "stat.cycle_aging": "Vieillissement normal",
    "stat.cycle_check": "Vérification conseillée",
    "stat.health": "Santé",
    "stat.health_excellent": "Excellent",
    "stat.health_good": "Bon",
    "stat.condition": "État",
    "stat.system_check": "Diagnostic système",
    "condition.normal": "Normal",
    "condition.replace_soon": "Remplacement conseillé",
    "condition.replace_now": "Remplacer maintenant",
    "rt.title": "Moniteur temps réel",
    "rt.voltage": "Tension",
    "rt.amperage": "Courant",
    "rt.power": "Puissance",
    "rt.temperature": "Temp",
    "rt.percent": "Niveau",
    "rt.30s": "30s",
    "rt.1m": "1m",
    "rt.3m": "3m",
    "rt.interval": "Échantillon toutes les 3s",
    "rt.collecting": "Collecte de données...",
    "rt.collecting_hint": "Échantillonnage toutes les 3 secondes",
    "rt.time": "Temps",
    "rt.y_voltage": "Tension (V)",
    "rt.y_amperage": "Courant (mA)",
    "rt.y_power": "Puissance (W)",
    "rt.y_temperature": "Temp (°C)",
    "rt.y_percent": "Niveau (%)",
    "hist.title": "Historique charge",
    "hist.refresh": "Actualiser",
    "hist.analyzing": "Analyse du journal...",
    "hist.empty": "Aucun historique",
    "hist.empty_hint": "Chargez puis actualisez",
    "hist.rate_chart": "Comparaison vitesse (%/h)",
    "hist.rate_unit": "%/h",
    "hist.duration": "%d min · %@",
    "proc.title": "Processus gourmands",
    "proc.refresh": "Actualiser",
    "proc.cpu_live": "CPU% · Direct",
    "proc.loading": "Chargement...",
    "proc.cpu_trend": "Tendance CPU",
    "proc.peak": "Pic",
    "proc.avg": "Moy",
    "proc.interval": "Toutes 5s · %d pts",
    "proc.collecting": "Collecte d'échantillons…",
    "usage.heavy": "Usage intensif",
    "usage.moderate": "Usage modéré",
    "usage.light": "Usage léger",
    "usage.idle": "Veille/Inactif",
    "tip.charge_power": "Puissance en watts entrant ou sortant de la batterie. Positif = charge, négatif = décharge.",
    "tip.adapter": "Puissance nominale de l'adaptateur connecté. 0W = aucun adaptateur détecté.",
    "tip.temperature": "Température actuelle des cellules. Plage normale 20–35°C. Au-delà de 40°C, bridage possible.",
    "tip.cycles": "Nombre total de cycles de charge. Apple garantit ~1000 cycles avant santé < 80%.",
    "tip.health": "Capacité max actuelle vs capacité d'origine. 100% = neuf. < 80% = remplacement conseillé.",
    "tip.condition": "Évaluation système basée sur la santé et les cycles.",
    "tip.voltage": "Tension aux bornes de la batterie. Plage typique MacBook : 10–13V.",
    "tip.amperage": "Courant de charge/décharge en mA. Positif = charge, négatif = décharge.",
    "tip.power": "Puissance instantanée = |Courant| × Tension.",
    "tip.percent": "Pourcentage de charge restante par rapport à la capacité utilisable.",
    "tip.charge_rate": "Pourcentage gagné par heure. Plus élevé = charge plus rapide.",
    "tip.cpu": "Utilisation CPU de ce processus. Plus élevée = plus de consommation.",
    "calculating": "Calcul...",
],

"es": [
    "app.title": "Monitor de Batería",
    "app.subtitle": "Panel de batería en tiempo real",
    "app.subtitle.model": "%@ · Panel en tiempo real",
    "app.live": "EN VIVO",
    "status.charging": "Cargando %.1fW · Adaptador %dW",
    "status.ac_full": "Conectado · Batería llena",
    "status.ac_not_charging": "Conectado · Sin cargar",
    "status.discharging": "Desconectado · Descarga %.1fW",
    "gauge.full": "llena",
    "gauge.ac": "Corriente",
    "gauge.battery": "En batería",
    "gauge.cycles_unit": "ciclos",
    "gauge.a11y_label": "Nivel de batería",
    "gauge.a11y_charging": "Cargando",
    "gauge.a11y_battery": "En batería",
    "stat.charge_power": "Potencia carga",
    "stat.discharge_power": "Potencia descarga",
    "stat.realtime_charging": "Activa",
    "stat.not_charging": "Inactiva",
    "stat.on_battery": "En batería",
    "stat.adapter": "Adaptador",
    "stat.not_connected": "N/A",
    "stat.usbc": "USB-C",
    "stat.unplugged": "Desconectado",
    "stat.temperature": "Temperatura",
    "stat.temp_high": "Alta",
    "stat.temp_normal": "Normal",
    "stat.cycles": "Ciclos",
    "stat.cycle_good": "Buen estado",
    "stat.cycle_aging": "Envejecimiento normal",
    "stat.cycle_check": "Revisión recomendada",
    "stat.health": "Salud",
    "stat.health_excellent": "Excelente",
    "stat.health_good": "Buena",
    "stat.condition": "Estado",
    "stat.system_check": "Diagnóstico sistema",
    "condition.normal": "Normal",
    "condition.replace_soon": "Reemplazo recomendado",
    "condition.replace_now": "Reemplazar ahora",
    "rt.title": "Monitor en vivo",
    "rt.voltage": "Voltaje",
    "rt.amperage": "Corriente",
    "rt.power": "Potencia",
    "rt.temperature": "Temp",
    "rt.percent": "Nivel",
    "rt.30s": "30s",
    "rt.1m": "1m",
    "rt.3m": "3m",
    "rt.interval": "Muestreo cada 3s",
    "rt.collecting": "Recopilando datos...",
    "rt.collecting_hint": "Muestreo cada 3 segundos",
    "rt.time": "Tiempo",
    "rt.y_voltage": "Voltaje (V)",
    "rt.y_amperage": "Corriente (mA)",
    "rt.y_power": "Potencia (W)",
    "rt.y_temperature": "Temp (°C)",
    "rt.y_percent": "Nivel (%)",
    "hist.title": "Historial de carga",
    "hist.refresh": "Actualizar",
    "hist.analyzing": "Analizando registro...",
    "hist.empty": "Sin historial",
    "hist.empty_hint": "Cargue y luego actualice",
    "hist.rate_chart": "Comparación velocidad (%/h)",
    "hist.rate_unit": "%/h",
    "hist.duration": "%d min · %@",
    "proc.title": "Procesos consumidores",
    "proc.refresh": "Actualizar",
    "proc.cpu_live": "CPU% · Vivo",
    "proc.loading": "Cargando procesos...",
    "proc.cpu_trend": "Tendencia CPU",
    "proc.peak": "Pico",
    "proc.avg": "Prom",
    "proc.interval": "Cada 5s · %d pts",
    "proc.collecting": "Recopilando muestras…",
    "usage.heavy": "Uso intensivo",
    "usage.moderate": "Uso moderado",
    "usage.light": "Uso ligero",
    "usage.idle": "Reposo/Inactivo",
    "tip.charge_power": "Potencia en vatios entrando o saliendo de la batería. Positivo = carga, negativo = descarga.",
    "tip.adapter": "Potencia nominal del adaptador conectado. 0W = sin adaptador.",
    "tip.temperature": "Temperatura actual de las celdas. Rango normal 20–35°C. Sobre 40°C posible limitación.",
    "tip.cycles": "Ciclos totales de carga. Apple diseña para ~1000 ciclos antes de salud < 80%.",
    "tip.health": "Capacidad máxima actual vs capacidad de diseño. 100% = nuevo. < 80% = reemplazo.",
    "tip.condition": "Evaluación del sistema basada en salud y ciclos.",
    "tip.voltage": "Voltaje en bornes de la batería. Rango típico MacBook: 10–13V.",
    "tip.amperage": "Corriente de carga/descarga en mA. Positivo = carga, negativo = descarga.",
    "tip.power": "Potencia instantánea = |Corriente| × Voltaje.",
    "tip.percent": "Porcentaje de carga restante respecto a capacidad utilizable.",
    "tip.charge_rate": "Porcentaje ganado por hora. Mayor = carga más rápida.",
    "tip.cpu": "Uso de CPU de este proceso. Mayor = más consumo.",
    "calculating": "Calculando...",
],

"de": [
    "app.title": "Batterie-Monitor",
    "app.subtitle": "Echtzeit-Batterie-Dashboard",
    "app.subtitle.model": "%@ · Echtzeit-Dashboard",
    "app.live": "LIVE",
    "status.charging": "Lädt mit %.1fW · Adapter %dW",
    "status.ac_full": "Verbunden · Voll geladen",
    "status.ac_not_charging": "Verbunden · Kein Laden",
    "status.discharging": "Getrennt · Entladung %.1fW",
    "gauge.full": "voll",
    "gauge.ac": "Netzbetrieb",
    "gauge.battery": "Akkubetrieb",
    "gauge.cycles_unit": "Zyklen",
    "gauge.a11y_label": "Akkustand",
    "gauge.a11y_charging": "Lädt",
    "gauge.a11y_battery": "Akkubetrieb",
    "stat.charge_power": "Ladeleistung",
    "stat.discharge_power": "Entladeleistung",
    "stat.realtime_charging": "Aktiv",
    "stat.not_charging": "Inaktiv",
    "stat.on_battery": "Akkubetrieb",
    "stat.adapter": "Adapter",
    "stat.not_connected": "N/A",
    "stat.usbc": "USB-C",
    "stat.unplugged": "Getrennt",
    "stat.temperature": "Temperatur",
    "stat.temp_high": "Hoch",
    "stat.temp_normal": "Normal",
    "stat.cycles": "Zyklen",
    "stat.cycle_good": "Guter Zustand",
    "stat.cycle_aging": "Normale Alterung",
    "stat.cycle_check": "Prüfung empfohlen",
    "stat.health": "Zustand",
    "stat.health_excellent": "Ausgezeichnet",
    "stat.health_good": "Gut",
    "stat.condition": "Batteriezustand",
    "stat.system_check": "Systemprüfung",
    "condition.normal": "Normal",
    "condition.replace_soon": "Austausch empfohlen",
    "condition.replace_now": "Jetzt ersetzen",
    "rt.title": "Echtzeit-Monitor",
    "rt.voltage": "Spannung",
    "rt.amperage": "Strom",
    "rt.power": "Leistung",
    "rt.temperature": "Temp",
    "rt.percent": "Stand",
    "rt.30s": "30s",
    "rt.1m": "1m",
    "rt.3m": "3m",
    "rt.interval": "Abtastung alle 3s",
    "rt.collecting": "Daten werden erfasst...",
    "rt.collecting_hint": "Abtastung alle 3 Sekunden",
    "rt.time": "Zeit",
    "rt.y_voltage": "Spannung (V)",
    "rt.y_amperage": "Strom (mA)",
    "rt.y_power": "Leistung (W)",
    "rt.y_temperature": "Temp (°C)",
    "rt.y_percent": "Stand (%)",
    "hist.title": "Ladeverlauf",
    "hist.refresh": "Aktualisieren",
    "hist.analyzing": "Ladeprotokoll wird analysiert...",
    "hist.empty": "Kein Ladeverlauf",
    "hist.empty_hint": "Laden und dann aktualisieren",
    "hist.rate_chart": "Ladegeschwindigkeit (%/h)",
    "hist.rate_unit": "%/h",
    "hist.duration": "%d Min · %@",
    "proc.title": "Energieverbrauch Prozesse",
    "proc.refresh": "Aktualisieren",
    "proc.cpu_live": "CPU% · Live",
    "proc.loading": "Prozesse laden...",
    "proc.cpu_trend": "CPU-Trend",
    "proc.peak": "Spitze",
    "proc.avg": "Mittel",
    "proc.interval": "Alle 5s · %d Pkt",
    "proc.collecting": "Proben werden erfasst…",
    "usage.heavy": "Starke Nutzung",
    "usage.moderate": "Mäßige Nutzung",
    "usage.light": "Leichte Nutzung",
    "usage.idle": "Ruhe/Leerlauf",
    "tip.charge_power": "Lade-/Entladeleistung in Watt. Positiv = Laden, negativ = Entladen.",
    "tip.adapter": "Nennleistung des angeschlossenen Adapters. 0W = kein Adapter erkannt.",
    "tip.temperature": "Aktuelle Zelltemperatur. Normalbereich 20–35°C. Über 40°C mögliche Drosselung.",
    "tip.cycles": "Gesamte Ladezyklen. Apple spezifiziert ~1000 Zyklen bis Gesundheit < 80%.",
    "tip.health": "Aktuelle Maxkapazität vs. Designkapazität. 100% = neu. < 80% = Austausch.",
    "tip.condition": "Systembewertung basierend auf Gesundheit und Zyklen.",
    "tip.voltage": "Batteriespannung an den Klemmen. Typischer MacBook-Bereich: 10–13V.",
    "tip.amperage": "Lade-/Entladestrom in mA. Positiv = Laden, negativ = Entladen.",
    "tip.power": "Momentanleistung = |Strom| × Spannung.",
    "tip.percent": "Aktueller Ladestand in Prozent der nutzbaren Kapazität.",
    "tip.charge_rate": "Prozent pro Stunde. Höher = schnelleres Laden.",
    "tip.cpu": "CPU-Auslastung dieses Prozesses. Höher = mehr Verbrauch.",
    "calculating": "Berechnung...",
],

"pt": [
    "app.title": "Monitor de Bateria",
    "app.subtitle": "Painel de bateria em tempo real",
    "app.subtitle.model": "%@ · Painel em tempo real",
    "app.live": "AO VIVO",
    "status.charging": "Carregando %.1fW · Adaptador %dW",
    "status.ac_full": "Conectado · Bateria cheia",
    "status.ac_not_charging": "Conectado · Sem carregar",
    "status.discharging": "Desconectado · Descarga %.1fW",
    "gauge.full": "cheia",
    "gauge.ac": "Energia",
    "gauge.battery": "Na bateria",
    "gauge.cycles_unit": "ciclos",
    "gauge.a11y_label": "Nível da bateria",
    "gauge.a11y_charging": "Carregando",
    "gauge.a11y_battery": "Na bateria",
    "stat.charge_power": "Potência carga",
    "stat.discharge_power": "Potência descarga",
    "stat.realtime_charging": "Ativa",
    "stat.not_charging": "Inativa",
    "stat.on_battery": "Na bateria",
    "stat.adapter": "Adaptador",
    "stat.not_connected": "N/A",
    "stat.usbc": "USB-C",
    "stat.unplugged": "Desconectado",
    "stat.temperature": "Temperatura",
    "stat.temp_high": "Alta",
    "stat.temp_normal": "Normal",
    "stat.cycles": "Ciclos",
    "stat.cycle_good": "Bom estado",
    "stat.cycle_aging": "Envelhecimento normal",
    "stat.cycle_check": "Verificação recomendada",
    "stat.health": "Saúde",
    "stat.health_excellent": "Excelente",
    "stat.health_good": "Boa",
    "stat.condition": "Condição",
    "stat.system_check": "Diagnóstico sistema",
    "condition.normal": "Normal",
    "condition.replace_soon": "Substituição recomendada",
    "condition.replace_now": "Substituir agora",
    "rt.title": "Monitor em tempo real",
    "rt.voltage": "Tensão",
    "rt.amperage": "Corrente",
    "rt.power": "Potência",
    "rt.temperature": "Temp",
    "rt.percent": "Nível",
    "rt.30s": "30s",
    "rt.1m": "1m",
    "rt.3m": "3m",
    "rt.interval": "Amostragem a cada 3s",
    "rt.collecting": "Coletando dados...",
    "rt.collecting_hint": "Amostragem a cada 3 segundos",
    "rt.time": "Tempo",
    "rt.y_voltage": "Tensão (V)",
    "rt.y_amperage": "Corrente (mA)",
    "rt.y_power": "Potência (W)",
    "rt.y_temperature": "Temp (°C)",
    "rt.y_percent": "Nível (%)",
    "hist.title": "Histórico de carga",
    "hist.refresh": "Atualizar",
    "hist.analyzing": "Analisando registro...",
    "hist.empty": "Sem histórico",
    "hist.empty_hint": "Carregue e atualize",
    "hist.rate_chart": "Comparação velocidade (%/h)",
    "hist.rate_unit": "%/h",
    "hist.duration": "%d min · %@",
    "proc.title": "Processos consumidores",
    "proc.refresh": "Atualizar",
    "proc.cpu_live": "CPU% · Ao vivo",
    "proc.loading": "Carregando processos...",
    "proc.cpu_trend": "Tendência CPU",
    "proc.peak": "Pico",
    "proc.avg": "Méd",
    "proc.interval": "Cada 5s · %d pts",
    "proc.collecting": "Coletando amostras…",
    "usage.heavy": "Uso intenso",
    "usage.moderate": "Uso moderado",
    "usage.light": "Uso leve",
    "usage.idle": "Repouso/Inativo",
    "tip.charge_power": "Potência em watts entrando ou saindo da bateria. Positivo = carga, negativo = descarga.",
    "tip.adapter": "Potência nominal do adaptador conectado. 0W = nenhum adaptador.",
    "tip.temperature": "Temperatura atual das células. Faixa normal 20–35°C. Acima de 40°C possível limitação.",
    "tip.cycles": "Ciclos totais de carga. Apple projeta ~1000 ciclos antes de saúde < 80%.",
    "tip.health": "Capacidade máxima atual vs capacidade de projeto. 100% = novo. < 80% = substituir.",
    "tip.condition": "Avaliação do sistema com base na saúde e ciclos.",
    "tip.voltage": "Tensão nos terminais da bateria. Faixa típica MacBook: 10–13V.",
    "tip.amperage": "Corrente de carga/descarga em mA. Positivo = carga, negativo = descarga.",
    "tip.power": "Potência instantânea = |Corrente| × Tensão.",
    "tip.percent": "Percentual de carga restante em relação à capacidade utilizável.",
    "tip.charge_rate": "Percentual ganho por hora. Maior = carga mais rápida.",
    "tip.cpu": "Uso de CPU deste processo. Maior = mais consumo.",
    "calculating": "Calculando...",
],

"it": [
    "app.title": "Monitor Batteria",
    "app.subtitle": "Dashboard batteria in tempo reale",
    "app.subtitle.model": "%@ · Dashboard in tempo reale",
    "app.live": "LIVE",
    "status.charging": "Carica %.1fW · Adattatore %dW",
    "status.ac_full": "Connesso · Batteria piena",
    "status.ac_not_charging": "Connesso · Non in carica",
    "status.discharging": "Scollegato · Scarica %.1fW",
    "gauge.full": "piena",
    "gauge.ac": "Alimentazione",
    "gauge.battery": "Su batteria",
    "gauge.cycles_unit": "cicli",
    "gauge.a11y_label": "Livello batteria",
    "gauge.a11y_charging": "In carica",
    "gauge.a11y_battery": "Su batteria",
    "stat.charge_power": "Potenza carica",
    "stat.discharge_power": "Potenza scarica",
    "stat.realtime_charging": "Attiva",
    "stat.not_charging": "Inattiva",
    "stat.on_battery": "Su batteria",
    "stat.adapter": "Adattatore",
    "stat.not_connected": "N/A",
    "stat.usbc": "USB-C",
    "stat.unplugged": "Scollegato",
    "stat.temperature": "Temperatura",
    "stat.temp_high": "Alta",
    "stat.temp_normal": "Normale",
    "stat.cycles": "Cicli",
    "stat.cycle_good": "Buono stato",
    "stat.cycle_aging": "Invecchiamento normale",
    "stat.cycle_check": "Controllo consigliato",
    "stat.health": "Salute",
    "stat.health_excellent": "Eccellente",
    "stat.health_good": "Buona",
    "stat.condition": "Condizione",
    "stat.system_check": "Diagnosi sistema",
    "condition.normal": "Normale",
    "condition.replace_soon": "Sostituzione consigliata",
    "condition.replace_now": "Sostituire ora",
    "rt.title": "Monitor in tempo reale",
    "rt.voltage": "Tensione",
    "rt.amperage": "Corrente",
    "rt.power": "Potenza",
    "rt.temperature": "Temp",
    "rt.percent": "Livello",
    "rt.30s": "30s",
    "rt.1m": "1m",
    "rt.3m": "3m",
    "rt.interval": "Campionamento ogni 3s",
    "rt.collecting": "Raccolta dati...",
    "rt.collecting_hint": "Campionamento ogni 3 secondi",
    "rt.time": "Tempo",
    "rt.y_voltage": "Tensione (V)",
    "rt.y_amperage": "Corrente (mA)",
    "rt.y_power": "Potenza (W)",
    "rt.y_temperature": "Temp (°C)",
    "rt.y_percent": "Livello (%)",
    "hist.title": "Cronologia carica",
    "hist.refresh": "Aggiorna",
    "hist.analyzing": "Analisi registro...",
    "hist.empty": "Nessuna cronologia",
    "hist.empty_hint": "Carica e poi aggiorna",
    "hist.rate_chart": "Confronto velocità (%/h)",
    "hist.rate_unit": "%/h",
    "hist.duration": "%d min · %@",
    "proc.title": "Processi consumatori",
    "proc.refresh": "Aggiorna",
    "proc.cpu_live": "CPU% · Live",
    "proc.loading": "Caricamento processi...",
    "proc.cpu_trend": "Tendenza CPU",
    "proc.peak": "Picco",
    "proc.avg": "Media",
    "proc.interval": "Ogni 5s · %d pts",
    "proc.collecting": "Raccolta campioni…",
    "usage.heavy": "Uso intenso",
    "usage.moderate": "Uso moderato",
    "usage.light": "Uso leggero",
    "usage.idle": "Riposo/Inattivo",
    "tip.charge_power": "Potenza in watt in entrata o uscita dalla batteria. Positivo = carica, negativo = scarica.",
    "tip.adapter": "Potenza nominale dell'adattatore collegato. 0W = nessun adattatore.",
    "tip.temperature": "Temperatura attuale delle celle. Intervallo normale 20–35°C. Oltre 40°C possibile limitazione.",
    "tip.cycles": "Cicli di carica totali. Apple progetta per ~1000 cicli prima di salute < 80%.",
    "tip.health": "Capacità massima attuale vs capacità di progetto. 100% = nuovo. < 80% = sostituire.",
    "tip.condition": "Valutazione del sistema basata su salute e cicli.",
    "tip.voltage": "Tensione ai terminali della batteria. Intervallo tipico MacBook: 10–13V.",
    "tip.amperage": "Corrente di carica/scarica in mA. Positivo = carica, negativo = scarica.",
    "tip.power": "Potenza istantanea = |Corrente| × Tensione.",
    "tip.percent": "Percentuale di carica rimanente rispetto alla capacità utilizzabile.",
    "tip.charge_rate": "Percentuale guadagnata per ora. Più alto = carica più veloce.",
    "tip.cpu": "Utilizzo CPU di questo processo. Più alto = più consumo.",
    "calculating": "Calcolo...",
],
]
